format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$git_metrics\
$cmd_duration\
$line_break\
$jobs\
$python\
$character"""

[directory]
style = "#B18AE8"
 
[character]
success_symbol = "[❯](#50FA7B)"
error_symbol = "[❯](#FF5555)"
vicmd_symbol = "[❮](#6272A4)"

[git_branch]
format = "[$branch(:$remote_branch)]($style)"
style = "#6272A4"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
style = "#8BE9FD"
conflicted = ""
untracked = ""
modified = ""
staged = ""
renamed = ""
deleted = ""
stashed = "≡"

[git_metrics]
disabled=false
format = "( [+$added]($added_style) )( [-$deleted]($deleted_style) )"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[cmd_duration]
format = "[$duration]($style) "
style = "#BD93F9"

[python]
format = "[${version}( $virtualenv)]($style) "
version_format = "${major}.${minor}"
style = "#ABB2BF"
pyenv_version_name = true

[jobs]
symbol = '󰑮'
symbol_threshold = 1
