font_family                 Latin Modern Mono Prop

background_opacity          0.75

map super+shift+return      new_os_window_with_cwd

# For NNN preview-tui
allow_remote_control yes
listen_on unix:/tmp/kitty
enabled_layouts splits
