format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$git_metrics\
$cmd_duration\
$line_break\
$python\
$character"""

[directory]
style = "#A7C080"
 
[character]
success_symbol = "[❯](#D3C6AA)"
error_symbol = "[❯](#E67E80)"
vicmd_symbol = "[❮](#7FBBB3)"

[git_branch]
format = "[$branch(:$remote_branch)]($style)"
style = "#9DA9A0"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
style = "#7FBBB3"
conflicted = ""
untracked = ""
modified = ""
staged = ""
renamed = ""
deleted = ""
stashed = "≡"

[git_metrics]
disabled=false
format = "( [+$added]($added_style) )( [-$deleted]($deleted_style) )"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[cmd_duration]
format = "[$duration]($style) "
style = "#A7C080"

[python]
format = "[${version}( $virtualenv)]($style) "
version_format = "${major}.${minor}"
style = "#9DA9A0"
pyenv_version_name = true
